### PR TITLE
Add CRA support

### PR DESCRIPTION
**Pull request by pcd1193182**
This patch adds CRA support to the recovery environment.

### CODE REVIEW

**Comment by pzakha** [comment]
What's our policy for the usage of PAM in the boot environment? Is this something that we need to have enabled as per the Delphix security policy?

The reason I'm asking is if we have some issues with PAM the recovery environment would be a way to connect to the system and fix PAM, but if we have PAM disabled recovering the system would be much more complicated.

**Comment by pcd1193182** [comment]
@pzakha my understanding is that we want to have CRA enabled in the reocvery env if we have it in the product for security reasons, otherwise a few quick reboots cause the system to become vulnerable.

**Comment by prakashsurya** [comment]
> I think whoever has the ability of rebooting the engine several times

IIRC, the ability to trigger a reboot is available in the UI; and I think it's common to have access to the UI, but not have access to the underlying disks.. I don't know if it's possible to trigger a reboot multiple times in quick succession via the UI, such that the recovery environment would kick in, though.

**Comment by pcd1193182** [comment]
The security team has recommended that we leave CRA disabled in the recovery environment, at least for now. Closing this PR.

**Pull request closed without merging**
